### ISSUE TITLE
How to build for Sailfish 3.3?

### ISSUE THREAD

**Issue by enigma9o7** [krnlyng/xbmc#1]
I've never used Sailfish SDK before, but since kodi no longer works, I wondered if it might just be as simple as rebuilding it.  So I installed sfos sdk, cloned this repo, tried 'sfdk build' but it fails complaining about needing a spec file.

**Comment by krnlyng** [comment]
Hi,

This was based on work from a different person who added wayland support for kodi, i think it might be better to start from scratch with the upstream version which might have wayland support by now.

I only ported it to SailfishOS and added a few quick customizations.

It's been a long time since i built this so i don't remember where i put the spec file, i'm sorry, i'll see what i can do about that.

**Comment by krnlyng** [comment]
https://github.com/krnlyng/xbmc-packaging

Here is the packaging. It's a bit broken but should give you what you want.

I have also updated the kodi rpms on openrepos.

**Comment by enigma9o7** [comment]
Much Thanks!  For updated version too!
